import Head from "next/head"
import Link from "next/link"
import Layout from "../components/layout"
import Date from "../components/date"
import { getSortedPostsData } from "../lib/posts"
import { IPost } from "../@types"

export async function getStaticProps() {
    const allPostsData = getSortedPostsData()
    return {
        props: {
            allPostsData,
        },
    }
}

export default function Home({ allPostsData }: { allPostsData: IPost[] }) {
    return (
        <Layout home>
            <Head>
                <title>Bruhwser</title>
                <meta
                    name='description'
                    content='Generated by create next app'
                />
            </Head>

            <section className='text-lg p-1'>
                <h2 className='text-xl text-center underline'>Blogs</h2>
                <ul className='text-center'>
                    {allPostsData.map(({ id, date, title }) => (
                        <li className='text-red-800' key={id}>
                            <Link href={`/posts/${id}`}>
                                <a>{title}</a>
                            </Link>
                            <div className='font-light'>
                                <Date dateString={date} />
                            </div>
                        </li>
                    ))}
                </ul>
            </section>
        </Layout>
    )
}
